### ISSUE TITLE
few tests failing

### ISSUE THREAD

**Issue by igor-raits** [carlos-jenkins/pydotplus#2]
``` python
======================================================================
FAIL: test_graph_with_shapefiles (__main__.TestGraphAPI)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "pydot_unittest.py", line 170, in test_graph_with_shapefiles
    self.assertEqual(hexdigest, hexdigest_original)
AssertionError: '7ce636bc45b33251bd7a49f3cdd6f1330f83405392cc0882f3fcb9b42cc94247' != '184094cbd7af28dcdb10c34442b6f73600d37c395fd6a95ee45e4039e0fba877'
- 7ce636bc45b33251bd7a49f3cdd6f1330f83405392cc0882f3fcb9b42cc94247
+ 184094cbd7af28dcdb10c34442b6f73600d37c395fd6a95ee45e4039e0fba877


======================================================================
FAIL: test_graphviz_regression_tests (__main__.TestGraphAPI)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "pydot_unittest.py", line 229, in test_graphviz_regression_tests
    self._render_and_compare_dot_files(REGRESSION_TESTS_DIR)
  File "pydot_unittest.py", line 254, in _render_and_compare_dot_files
    self.assertEqual(parsed_data_hexdigest, original_data_hexdigest)
AssertionError: 'e077ef38757bf7e88766a0607b70bd733b843e184a2e86b2569e1ab7276d77a1' != '5f4189353deaea8ecaac4f590396ac13667f68db8e342cd08545c97acdcde35f'
- e077ef38757bf7e88766a0607b70bd733b843e184a2e86b2569e1ab7276d77a1
+ 5f4189353deaea8ecaac4f590396ac13667f68db8e342cd08545c97acdcde35f
```

**Comment by peternowee** [comment]
While investigating a similar-looking issue for pydot, I looked into these issues in pydotplus. Although I found they were not related to the pydot issue, I thought I would share my findings:

- Pydotplus issues carlos-jenkins/pydotplus#2 and carlos-jenkins/pydotplus#22 are most likely duplicates.
- The original DOT files for the failing tests ([`fig6.dot`](https://github.com/carlos-jenkins/pydotplus/blob/e06552ea3989bfb998ef6920a07d6c966ff9b01b/test/graphs/fig6.dot) and [`from-past-to-future.dot`](https://github.com/carlos-jenkins/pydotplus/blob/e06552ea3989bfb998ef6920a07d6c966ff9b01b/test/from-past-to-future/from-past-to-future.dot)) both contain multiple subgraphs with `rank=` attributes. In both cases, the subgraphs have no ID (name). When Graphviz processes the original DOT file directly, it retains the multiple subgraphs separately, still without ID.
- However, when pydotplus parses and then writes out a DOT file again, it uses two double quotes (`""`) as the ID of the subgraphs. Then when Graphviz subsequently processes that pydotplus DOT output, it considers all subgraphs with ID `""` to be referring to the same subgraph and merges them into a single subgraph with ID `""` containing all the `rank=` attributes of the previously multiple subgraphs.
- The `""` was introduced by commit carlos-jenkins/pydotplus@13686776b902056e6898db0036535612e58755a6 (2014). I checked that reverting that commit resolves the test failures.
- Commit pydot/pydot-ng@13686776b902056e6898db0036535612e58755a6 was also part of pydot-ng (another fork of pydot), but was reverted there in commit pydot/pydot-ng@1c30938866085bdfe39ddb09167d3a8f4f95a70e (2018) since "it introduced a lot regressions" and "caused too much quotes to be added to DOT representation of the graph which made graphs broken".
- The original pydot never fully implemented `13686776`, but rather chose to replace only empty attribute values, not IDs, with `""` in pydot/pydot@cecf60a5ac8f9d75119354752dad7f670df24742 (2016).

As by this time I had concluded that the two issues here at pydotplus were not related to the pydot issue I was investigating, I did not investigate any further.
