### ISSUE TITLE
Two unit tests fail with inconsistent checksums

### ISSUE THREAD

**Issue by TheChymera** [carlos-jenkins/pydotplus#22]
Any idea what's happening here?

```
chymera@silenthost ~/src/pydotplus/test $ python pydot_unittest.py
test_add_style (__main__.TestGraphAPI) ... ok
test_attribute_with_implicit_value (__main__.TestGraphAPI) ... ok
test_create_simple_graph_with_node (__main__.TestGraphAPI) ... ok
test_executable_not_found_exception (__main__.TestGraphAPI) ... ok
test_graph_add_edge_argument_type (__main__.TestGraphAPI) ... ok
test_graph_add_node_argument_type (__main__.TestGraphAPI) ... ok
test_graph_add_subgraph_argument_type (__main__.TestGraphAPI) ... ok
test_graph_pickling (__main__.TestGraphAPI) ... ok
test_graph_with_shapefiles (__main__.TestGraphAPI) ... FAIL
test_graphviz_regression_tests (__main__.TestGraphAPI) ... ###Warning: slate_blue is not a known color.
Warning: hot pink is not a known color.

#######Warning: using box for unknown shape DFDbox

#BAD(fig6.dot)
FAIL
test_keep_graph_type (__main__.TestGraphAPI) ... ok
test_keyword_node_id (__main__.TestGraphAPI) ... ok
test_keyword_node_id_to_string_no_attributes (__main__.TestGraphAPI) ... ok
test_keyword_node_id_to_string_with_attributes (__main__.TestGraphAPI) ... ok
test_multiple_graphs (__main__.TestGraphAPI) ... ok
test_my_regression_tests (__main__.TestGraphAPI) ... ####ok
test_names_of_a_thousand_nodes (__main__.TestGraphAPI) ... ok
test_numeric_node_id (__main__.TestGraphAPI) ... ok
test_quoted_node_id (__main__.TestGraphAPI) ... ok
test_quoted_node_id_to_string_no_attributes (__main__.TestGraphAPI) ... ok
test_quoting (__main__.TestGraphAPI) ... ok
test_subgraphs (__main__.TestGraphAPI) ... ok
test_unicode_ids (__main__.TestGraphAPI) ... ok

======================================================================
FAIL: test_graph_with_shapefiles (__main__.TestGraphAPI)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "pydot_unittest.py", line 170, in test_graph_with_shapefiles
    self.assertEqual(hexdigest, hexdigest_original)
AssertionError: 'a3f3a048bff6ece2cb00c2cab6c4e0b9575219a9a648cba2f006d9367d26ebaf' != '5cd877ac8b042ff51d4de63c236dad5830425a1047ece02221b0bf26bc93dca4'
- a3f3a048bff6ece2cb00c2cab6c4e0b9575219a9a648cba2f006d9367d26ebaf
+ 5cd877ac8b042ff51d4de63c236dad5830425a1047ece02221b0bf26bc93dca4


======================================================================
FAIL: test_graphviz_regression_tests (__main__.TestGraphAPI)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "pydot_unittest.py", line 229, in test_graphviz_regression_tests
    self._render_and_compare_dot_files(REGRESSION_TESTS_DIR)
  File "pydot_unittest.py", line 254, in _render_and_compare_dot_files
    self.assertEqual(parsed_data_hexdigest, original_data_hexdigest)
AssertionError: 'ff3d48cdc4db86923fa96c45f1259baaf291118196dd202ecf07767cbdd6a2c5' != 'b95a066e4d260744063a6adf46bce2de772219fcc0ed3dbddd801c6289ed6305'
- ff3d48cdc4db86923fa96c45f1259baaf291118196dd202ecf07767cbdd6a2c5
+ b95a066e4d260744063a6adf46bce2de772219fcc0ed3dbddd801c6289ed6305


----------------------------------------------------------------------
Ran 23 tests in 3.550s

FAILED (failures=2)
```

**Comment by peternowee** [comment]
I think this is a duplicate of https://github.com/carlos-jenkins/pydotplus/issues/2. I shared my findings there.
